api = "0.2"

[buildpack]
  id = "org.cloudfoundry.node-engine"
  name = "Node Engine Buildpack"
  version = "{{ .Version }}"

[metadata]
  include_files = ["bin/build", "bin/detect", "buildpack.toml"]
  pre_package = "./scripts/build.sh"
  [metadata.default-versions]
    node = "10.x"

  [[metadata.dependencies]]
    id = "node"
    name = "Node Engine"
    sha256 = "528414d1987c8ff9d74f6b5baef604632a2d1d1fbce4a33c7302debcbfa53e1b"
    source = "https://nodejs.org/dist/v10.18.1/node-v10.18.1-linux-x64.tar.gz"
    source_sha256 = "812fe7d421894b792027d19c78c919faad3bf32d8bc16bde67f5c7eea2469eac"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-10.18.1-bionic-528414d1.tgz"
    version = "10.18.1"

  [[metadata.dependencies]]
    id = "node"
    name = "Node Engine"
    sha256 = "ad0376cbe4dfc3d6092d0ea9fdc4fd3fcb44c477bd4a2c800ccd48eee95e994d"
    source = "https://nodejs.org/dist/v10.18.1/node-v10.18.1.tar.gz"
    source_sha256 = "80a61ffbe6d156458ed54120eb0e9fff7b626502e0986e861d91b365f7e876db"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-10.18.1-linux-x64-cflinuxfs3-ad0376cb.tgz"
    version = "10.18.1"

  [[metadata.dependencies]]
    id = "node"
    name = "Node Engine"
    sha256 = "75d08023c0121ae0c82dc124e459dcf09141440a304658aefa2de7b2f09937de"
    source = "https://nodejs.org/dist/v10.19.0/node-v10.19.0-linux-x64.tar.gz"
    source_sha256 = "36d90bc58f0418f31dceda5b18eb260019fcc91e59b0820ffa66700772a8804b"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-10.19.0-bionic-75d08023.tgz"
    version = "10.19.0"

  [[metadata.dependencies]]
    id = "node"
    name = "Node Engine"
    sha256 = "0bcac6860f8103e37d85a271898d019edb8d50ba7e3aaee50a0526684f962f10"
    source = "https://nodejs.org/dist/v10.19.0/node-v10.19.0.tar.gz"
    source_sha256 = "db85b9992f1ec66629731d82f690987883dd2989abb4cc136eb65dd720b1bda8"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-10.19.0-linux-x64-cflinuxfs3-0bcac686.tgz"
    version = "10.19.0"

  [[metadata.dependencies]]
    id = "node"
    name = "Node Engine"
    sha256 = "c623d3edfd3b69443ae26ac3f8c23db1bc42d9b4a7ab9ab68666f8c9828bd0b7"
    source = "https://nodejs.org/dist/v12.16.0/node-v12.16.0-linux-x64.tar.gz"
    source_sha256 = "fe8eca839b702f1ca47e9aabfd833cfa3e68952450d1f4c893cdfb0650ecd3c2"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-12.16.0-bionic-c623d3ed.tgz"
    version = "12.16.0"

  [[metadata.dependencies]]
    id = "node"
    name = "Node Engine"
    sha256 = "e4ed0bdcaeb440bd6a78b61c982890f71e7ba84933d6c9a21bda6e8a6a18cef5"
    source = "https://nodejs.org/dist/v12.16.0/node-v12.16.0.tar.gz"
    source_sha256 = "ae2dfe74485d821d4fef7cf1802acd2322cd994c853a2327c4306952f4453441"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-12.16.0-linux-x64-cflinuxfs3-e4ed0bdc.tgz"
    version = "12.16.0"

  [[metadata.dependencies]]
    id = "node"
    name = "Node Engine"
    sha256 = "ae67975b462a580000023ed9b461f6d91326fbb4c2781695c0da87857321edba"
    source = "https://nodejs.org/dist/v12.16.1/node-v12.16.1-linux-x64.tar.gz"
    source_sha256 = "b2d9787da97d6c0d5cbf24c69fdbbf376b19089f921432c5a61aa323bc070bea"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-12.16.1-bionic-ae67975b.tgz"
    version = "12.16.1"

  [[metadata.dependencies]]
    id = "node"
    name = "Node Engine"
    sha256 = "7bb532cc92e8c4422e5d56c16456b0b6a9cbfdbc4f328b428988e01b35b8fea8"
    source = "https://nodejs.org/dist/v12.16.1/node-v12.16.1.tar.gz"
    source_sha256 = "4fe8c3454f9bee5bbe72d44aa25cd931859b3037b7a9473081b3b2bd1b465b95"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-12.16.1-linux-x64-cflinuxfs3-7bb532cc.tgz"
    version = "12.16.1"

  [[metadata.dependencies]]
    id = "node"
    name = "Node Engine"
    sha256 = "8058f89fd0ee414c5f5ea40887b947dda16e12c928be7c226b3d51ebe2e0c1c1"
    source = "https://nodejs.org/dist/v13.7.0/node-v13.7.0-linux-x64.tar.gz"
    source_sha256 = "49ecb710e29c3ea0617803f450e2dc9b229688f1576190826ffdd5a9eaae7869"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-13.7.0-bionic-8058f89f.tgz"
    version = "13.7.0"

  [[metadata.dependencies]]
    id = "node"
    name = "Node Engine"
    sha256 = "54406edc94eb5b3c369bc9b669095208a4ee635609bb8b0fa38b0e4775df99d7"
    source = "https://nodejs.org/dist/v13.7.0/node-v13.7.0.tar.gz"
    source_sha256 = "441a1b2b6031f359597fb68b82fd27dfbbe5933f9e1242f6a03062c2abd88368"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-13.7.0-linux-x64-cflinuxfs3-54406edc.tgz"
    version = "13.7.0"

  [[metadata.dependencies]]
    id = "node"
    name = "Node Engine"
    sha256 = "da76b24cb5741a03fbf1f8503113c5e33d26ddc06717aa88f07a753f8a063d90"
    source = "https://nodejs.org/dist/v13.8.0/node-v13.8.0-linux-x64.tar.gz"
    source_sha256 = "bf30432175ea8a95fa3e5fe09e96d9fc17b07099742d5c83c4cf9d0edfc411ff"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-13.8.0-bionic-da76b24c.tgz"
    version = "13.8.0"

  [[metadata.dependencies]]
    id = "node"
    name = "Node Engine"
    sha256 = "d95d5c092a4cf52abe83eac5e2ebb171d1126023408dc8f280b031f34808cf9a"
    source = "https://nodejs.org/dist/v13.8.0/node-v13.8.0.tar.gz"
    source_sha256 = "815b5e1b18114f35da89e4d98febeaba97555d51ef593bd5175db2b05f2e8be6"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-13.8.0-linux-x64-cflinuxfs3-d95d5c09.tgz"
    version = "13.8.0"

  [[metadata.dependency_deprecation_dates]]
    date = 2021-04-01T00:00:00Z
    link = "https://github.com/nodejs/Release"
    name = "node"
    version_line = "10.x.x"

  [[metadata.dependency_deprecation_dates]]
    date = 2022-04-01T00:00:00Z
    link = "https://github.com/nodejs/Release"
    name = "node"
    version_line = "12.x.x"

  [[metadata.dependency_deprecation_dates]]
    date = 2020-06-01T00:00:00Z
    link = "https://github.com/nodejs/Release"
    name = "node"
    version_line = "13.x.x"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"
