
[buildpack]
id = "org.cloudfoundry.node-engine"
name = "Node Engine Buildpack"
version = "{{ .Version }}"

[metadata]
include_files = ["bin/build","bin/detect","buildpack.toml"]
pre_package = "./scripts/build.sh"

[metadata.default-versions]
node = "10.x"

[[metadata.dependencies]]
id = "node"
name = "Node Engine"
sha256 = "16e203f2440cffe90522f1e1855d5d7e2e658e759057db070a3dafda445d6d1f"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v8.15.1/node-v8.15.1-linux-x64.tar.gz"
version = "8.15.1"

[[metadata.dependencies]]
id = "node"
name = "Node Engine"
sha256 = "bed0d0e675f46be256f292e2bf693e59a82ea46eb4d9d593575483d0c4428312"
source = "https://nodejs.org/dist/v8.15.1/node-v8.15.1.tar.gz"
source_sha256 = "413e0086bd3abde2dfdd3a905c061a6188cc0faceb819768a53ca9c6422418b4"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-8.15.1-linux-x64-cflinuxfs3-bed0d0e6.tgz"
version = "8.15.1"

[[metadata.dependencies]]
id = "node"
name = "Node Engine"
sha256 = "b391450e0fead11f61f119ed26c713180cfe64b363cd945bac229130dfab64fa"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v8.16.0/node-v8.16.0-linux-x64.tar.gz"
version = "8.16.0"

[[metadata.dependencies]]
id = "node"
name = "Node Engine"
sha256 = "f190a0786c817d7749c3ec6e294f284104cd9a594e1989c59cafe08b41fe347c"
source = "https://nodejs.org/dist/v8.16.0/node-v8.16.0.tar.gz"
source_sha256 = "a1a885add3e511177f05676f0834df710886b68cb559b893169f8674a23adfcf"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-8.16.0-linux-x64-cflinuxfs2-f190a078.tgz"
version = "8.16.0"

[[metadata.dependencies]]
id = "node"
name = "Node Engine"
sha256 = "319b5cd2ca0172c4d427fd4f67df858756f04dff04f92670a4658703b9f03a75"
source = "https://nodejs.org/dist/v8.16.0/node-v8.16.0.tar.gz"
source_sha256 = "a1a885add3e511177f05676f0834df710886b68cb559b893169f8674a23adfcf"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-8.16.0-linux-x64-cflinuxfs3-319b5cd2.tgz"
version = "8.16.0"

[[metadata.dependencies]]
id = "node"
name = "Node Engine"
sha256 = "32db9700d2ba926e774c17e7cd8952499e64e241b095d22e05d3d62ebe4cb6d4"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v10.16.1/node-v10.16.1-linux-x64.tar.gz"
version = "10.16.1"

[[metadata.dependencies]]
id = "node"
name = "Node Engine"
sha256 = "90d7afe06325bc248927aebeb8dfb3267795fc10e441bf640b9ddc7ee24c2f4e"
source = "https://nodejs.org/dist/v10.16.1/node-v10.16.1.tar.gz"
source_sha256 = "98c92edcfced73b572917d01a53aa9deefec85d8a2fe96c46fe10ee1d0a7763d"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-10.16.1-linux-x64-cflinuxfs3-90d7afe0.tgz"
version = "10.16.1"

[[metadata.dependencies]]
id = "node"
name = "Node Engine"
sha256 = "2779d04b1a9744bbb003a1a4476db2444b5f697034bc902a07dde4a8669ae6d0"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v10.16.2/node-v10.16.2-linux-x64.tar.gz"
version = "10.16.2"

[[metadata.dependencies]]
id = "node"
name = "Node Engine"
sha256 = "9d21a165fedeccc9ffdd50657e51312e83ce7204370434d1cba9d02dc728c50a"
source = "https://nodejs.org/dist/v10.16.2/node-v10.16.2.tar.gz"
source_sha256 = "5936ef12ab3f0ce5fbb6751c1bb41f626b6058f414a297b3d8c5eb418a27e8fe"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-10.16.2-linux-x64-cflinuxfs3-9d21a165.tgz"
version = "10.16.2"

[[metadata.dependencies]]
id = "node"
name = "Node Engine"
sha256 = "78c12398128e79dfec3092325da026d422d296c9d3089a9b2ee7bf7bd2e3be87"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v12.3.1/node-v12.3.1-linux-x64.tar.gz"
version = "12.3.1"

[[metadata.dependencies]]
id = "node"
name = "Node Engine"
sha256 = "1d6cccfcf9c61904f23f3a9dc9ef7e373afa170f7030bc64564461a044f36439"
source = "https://nodejs.org/dist/v12.6.0/node-v12.6.0.tar.gz"
source_sha256 = "8b47a34a5507ee24abb91f26f8799bf3af66172b0ffd45981a7fcf1dde463bd4"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-12.6.0-linux-x64-cflinuxfs3-1d6cccfc.tgz"
version = "12.6.0"

[[metadata.dependencies]]
id = "node"
name = "Node Engine"
sha256 = "bc232791d839dd2159173ebedfdc22376e582a5f51a546e0f01de7182720e174"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v12.7.0/node-v12.7.0-linux-x64.tar.gz"
version = "12.7.0"

[[metadata.dependencies]]
id = "node"
name = "Node Engine"
sha256 = "2b32da9cc9cf8c5ac332d2f4a1989f60290e0317c3eeefe4ebbfbaefd6decb3a"
source = "https://nodejs.org/dist/v12.7.0/node-v12.7.0.tar.gz"
source_sha256 = "d5e63fd4ee88d539a69b9e71631d03014bd8e98596e741515e3d7aa930f4630a"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-12.7.0-linux-x64-cflinuxfs3-2b32da9c.tgz"
version = "12.7.0"

[[metadata.dependency_deprecation_dates]]
date = 2021-04-01T00:00:00Z
link = "https://github.com/nodejs/Release"
name = "node"
version_line = "10.x.x"

[[metadata.dependency_deprecation_dates]]
date = 2020-04-01T00:00:00Z
link = "https://github.com/nodejs/Release"
name = "node"
version_line = "12.x.x"

[[metadata.dependency_deprecation_dates]]
date = 2019-12-01T00:00:00Z
link = "https://github.com/nodejs/Release"
name = "node"
version_line = "8.x.x"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
id = "io.buildpacks.stacks.bionic"
