
[buildpack]
id = "org.cloudfoundry.node-engine"
name = "Node Engine Buildpack"
version = "{{ .Version }}"

[metadata]
include_files = ["bin/build","bin/detect","buildpack.toml"]
pre_package = "./scripts/build.sh"

[metadata.default-versions]
node = "10.x"

[[metadata.dependencies]]
id = "node"
name = "Node Engine"
sha256 = "b391450e0fead11f61f119ed26c713180cfe64b363cd945bac229130dfab64fa"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v8.16.0/node-v8.16.0-linux-x64.tar.gz"
version = "8.16.0"

[[metadata.dependencies]]
id = "node"
name = "Node Engine"
sha256 = "f190a0786c817d7749c3ec6e294f284104cd9a594e1989c59cafe08b41fe347c"
source = "https://nodejs.org/dist/v8.16.0/node-v8.16.0.tar.gz"
source_sha256 = "a1a885add3e511177f05676f0834df710886b68cb559b893169f8674a23adfcf"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-8.16.0-linux-x64-cflinuxfs2-f190a078.tgz"
version = "8.16.0"

[[metadata.dependencies]]
id = "node"
name = "Node Engine"
sha256 = "319b5cd2ca0172c4d427fd4f67df858756f04dff04f92670a4658703b9f03a75"
source = "https://nodejs.org/dist/v8.16.0/node-v8.16.0.tar.gz"
source_sha256 = "a1a885add3e511177f05676f0834df710886b68cb559b893169f8674a23adfcf"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-8.16.0-linux-x64-cflinuxfs3-319b5cd2.tgz"
version = "8.16.0"

[[metadata.dependencies]]
id = "node"
name = "Node Engine"
sha256 = "8ef575b64edbb6c04e506d8c8e0c5f92b90f4752841892c5adbb3a1e02863f46"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v8.16.1/node-v8.16.1-linux-x64.tar.gz"
version = "8.16.1"

[[metadata.dependencies]]
id = "node"
name = "Node Engine"
sha256 = "fbbdac757c69cf3ea80031ac916f99e768773ec74d3ffd38c6308b99e02414ee"
source = "https://nodejs.org/dist/v8.16.1/node-v8.16.1.tar.gz"
source_sha256 = "7666207212ac5cbd766b052951f57da62aaa641fedf83fabcb31dbb19f61169d"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-8.16.1-linux-x64-cflinuxfs3-fbbdac75.tgz"
version = "8.16.1"

[[metadata.dependencies]]
id = "node"
name = "Node Engine"
sha256 = "2779d04b1a9744bbb003a1a4476db2444b5f697034bc902a07dde4a8669ae6d0"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v10.16.2/node-v10.16.2-linux-x64.tar.gz"
version = "10.16.2"

[[metadata.dependencies]]
id = "node"
name = "Node Engine"
sha256 = "9d21a165fedeccc9ffdd50657e51312e83ce7204370434d1cba9d02dc728c50a"
source = "https://nodejs.org/dist/v10.16.2/node-v10.16.2.tar.gz"
source_sha256 = "5936ef12ab3f0ce5fbb6751c1bb41f626b6058f414a297b3d8c5eb418a27e8fe"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-10.16.2-linux-x64-cflinuxfs3-9d21a165.tgz"
version = "10.16.2"

[[metadata.dependencies]]
id = "node"
name = "Node Engine"
sha256 = "2f0397bb81c1d0c9901b9aff82a933257bf60f3992227b86107111a75b9030d9"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v10.16.3/node-v10.16.3-linux-x64.tar.gz"
version = "10.16.3"

[[metadata.dependencies]]
id = "node"
name = "Node Engine"
sha256 = "33294d3658fe726d2d035092c72d150b7bd7b6d7de2ecab8fed66862f1f6bafd"
source = "https://nodejs.org/dist/v10.16.3/node-v10.16.3.tar.gz"
source_sha256 = "db5a5e03a815b84a1266a4b48bb6a6d887175705f84fd2472f0d28e5e305a1f8"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-10.16.3-linux-x64-cflinuxfs3-33294d36.tgz"
version = "10.16.3"

[[metadata.dependencies]]
id = "node"
name = "Node Engine"
sha256 = "8758a131cac2e8a373153b9eb53696d2e823b910dbf175af7ec4a0592b065c22"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v12.8.1/node-v12.8.1-linux-x64.tar.gz"
version = "12.8.1"

[[metadata.dependencies]]
id = "node"
name = "Node Engine"
sha256 = "c7ab50ce2454af3fa81d0cd2fe9858443d75e0f2970b1b66a61b71431d42db44"
source = "https://nodejs.org/dist/v12.8.1/node-v12.8.1.tar.gz"
source_sha256 = "fbd4de6657f6301cdcd0c60a0e5a413c490670d8c21b501c380b96cc3b9b5b95"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-12.8.1-linux-x64-cflinuxfs3-c7ab50ce.tgz"
version = "12.8.1"

[[metadata.dependencies]]
id = "node"
name = "Node Engine"
sha256 = "3991e5b65fbaab8d70cda813b9bc73dd3b4201aeef42bcb1c000a03869aa0610"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v12.9.0/node-v12.9.0-linux-x64.tar.gz"
version = "12.9.0"

[[metadata.dependencies]]
id = "node"
name = "Node Engine"
sha256 = "9f9ca6a05bb18fcd21de3d87b171c756e108089cd6ef02db260d728704ec325c"
source = "https://nodejs.org/dist/v12.9.0/node-v12.9.0.tar.gz"
source_sha256 = "88cb425086a87323288c8389e974e8c1001b81fe11c529e64592e8feb2d12f93"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-12.9.0-linux-x64-cflinuxfs3-9f9ca6a0.tgz"
version = "12.9.0"

[[metadata.dependency_deprecation_dates]]
date = 2021-04-01T00:00:00Z
link = "https://github.com/nodejs/Release"
name = "node"
version_line = "10.x.x"

[[metadata.dependency_deprecation_dates]]
date = 2020-04-01T00:00:00Z
link = "https://github.com/nodejs/Release"
name = "node"
version_line = "12.x.x"

[[metadata.dependency_deprecation_dates]]
date = 2019-12-01T00:00:00Z
link = "https://github.com/nodejs/Release"
name = "node"
version_line = "8.x.x"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
id = "io.buildpacks.stacks.bionic"
