api = "0.2"

[buildpack]
  id = "org.cloudfoundry.node-engine"
  name = "Node Engine Buildpack"
  version = "{{ .Version }}"

[metadata]
  include_files = ["bin/build", "bin/detect", "buildpack.toml"]
  pre_package = "./scripts/build.sh"
  [metadata.default-versions]
    node = "10.x"

  [[metadata.dependencies]]
    id = "node"
    name = "Node Engine"
    sha256 = "722d07291a8886384388c6795a747ec2055073f83dc73c0a97efba0022cc23ff"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://nodejs.org/dist/v8.16.2/node-v8.16.2-linux-x64.tar.gz"
    version = "8.16.2"

  [[metadata.dependencies]]
    id = "node"
    name = "Node Engine"
    sha256 = "41238419bb4f3070bf5a31e83652c8506c79e392060e1b948fbdafd704b3a65f"
    source = "https://nodejs.org/dist/v8.16.2/node-v8.16.2.tar.gz"
    source_sha256 = "4f94361bbe087bc3a9d48ff69c2cefabb6460c64cb7d959204726467b9ee84b8"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-8.16.2-linux-x64-cflinuxfs3-41238419.tgz"
    version = "8.16.2"

  [[metadata.dependencies]]
    id = "node"
    name = "Node Engine"
    sha256 = "8b2c9e1f84317c4b02736c4c50db4dd2cd6c4f0ba910fa81f887c8c9294af596"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://nodejs.org/dist/v8.17.0/node-v8.17.0-linux-x64.tar.gz"
    version = "8.17.0"

  [[metadata.dependencies]]
    id = "node"
    name = "Node Engine"
    sha256 = "8570ccdaa36f2afe11985254d7916f60ddebe09e351a3006487145c6b6350001"
    source = "https://nodejs.org/dist/v8.17.0/node-v8.17.0.tar.gz"
    source_sha256 = "aa583f19065545fa4c9b480ba13cf94f29350415ca5a853a5afde3c9b6982c4b"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-8.17.0-linux-x64-cflinuxfs3-8570ccda.tgz"
    version = "8.17.0"

  [[metadata.dependencies]]
    id = "node"
    name = "Node Engine"
    sha256 = "417bdc5402f6510fe1a5a898a9cdf1d67bd0202b5f014051c382f05358999534"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://nodejs.org/dist/v10.17.0/node-v10.17.0-linux-x64.tar.gz"
    version = "10.17.0"

  [[metadata.dependencies]]
    id = "node"
    name = "Node Engine"
    sha256 = "1d19d6b0af72f2e396c1ed835c9318a06d107ea940c29818ecb82f4ef87242e5"
    source = "https://nodejs.org/dist/v10.17.0/node-v10.17.0.tar.gz"
    source_sha256 = "5204249d135176b547737d3eed2ca8a9d7f731fef6e545f741129cfa21f90573"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-10.17.0-linux-x64-cflinuxfs3-1d19d6b0.tgz"
    version = "10.17.0"

  [[metadata.dependencies]]
    id = "node"
    name = "Node Engine"
    sha256 = "78a46d1e1f6db68c0732981fc9a1fe8583eabb4e232f1ed742f7dedc5bed3ddd"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://nodejs.org/dist/v10.18.0/node-v10.18.0-linux-x64.tar.gz"
    version = "10.18.0"

  [[metadata.dependencies]]
    id = "node"
    name = "Node Engine"
    sha256 = "7242c51f0b49bd8e489b5a0b298cad9b4cd64ff3f0aec0d87b38eb7da9a2e980"
    source = "https://nodejs.org/dist/v10.18.0/node-v10.18.0.tar.gz"
    source_sha256 = "f9c8785c5d5ba0e5412dada04a89ab3fe32531423c47232217aad79757a769e7"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-10.18.0-linux-x64-cflinuxfs3-7242c51f.tgz"
    version = "10.18.0"

  [[metadata.dependencies]]
    id = "node"
    name = "Node Engine"
    sha256 = "c69671c89d0faa47b64bd5f37079e4480852857a9a9366ee86cdd8bc9670074a"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://nodejs.org/dist/v12.13.0/node-v12.13.0-linux-x64.tar.gz"
    version = "12.13.0"

  [[metadata.dependencies]]
    id = "node"
    name = "Node Engine"
    sha256 = "55d69507d240b1ce582ce1c66e675b2271d8c3585f76c453595b3f3f20f4ed09"
    source = "https://nodejs.org/dist/v12.13.0/node-v12.13.0.tar.gz"
    source_sha256 = "2e5321e095fe673a3ab936cf77faf8c983cba62f27a9fbd00530a7edb739a040"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-12.13.0-linux-x64-cflinuxfs3-55d69507.tgz"
    version = "12.13.0"

  [[metadata.dependencies]]
    id = "node"
    name = "Node Engine"
    sha256 = "074a6129da34b768b791f39e8b74c6e4ab3349d1296f1a303ef3547a7f9cf9be"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://nodejs.org/dist/v12.13.1/node-v12.13.1-linux-x64.tar.gz"
    version = "12.13.1"

  [[metadata.dependencies]]
    id = "node"
    name = "Node Engine"
    sha256 = "1e528ef48f0922b8fcb0a766edfaf6ececedd092964231f1eab3f8a97ed2a571"
    source = "https://nodejs.org/dist/v12.13.1/node-v12.13.1.tar.gz"
    source_sha256 = "4ee710087687c8de142329d95085f5cba66e454a2c9ea7ec11e1f4b476d6d1ac"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-12.13.1-linux-x64-cflinuxfs3-1e528ef4.tgz"
    version = "12.13.1"

  [[metadata.dependencies]]
    id = "node"
    name = "Node Engine"
    sha256 = "dcf3954ecf6a34d65cab277d3565c654996b1d3e6d07cbbd98939cee0792c668"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://nodejs.org/dist/v13.2.0/node-v13.2.0-linux-x64.tar.gz"
    version = "13.2.0"

  [[metadata.dependencies]]
    id = "node"
    name = "Node Engine"
    sha256 = "fd282407e3d81457e41cf2ea1c1b5c0d0e588b234bc7c8ff96df5a7323c76cad"
    source = "https://nodejs.org/dist/v13.2.0/node-v13.2.0.tar.gz"
    source_sha256 = "379dcecb721984a99dc9e16c2a096d6eb7a760d50b188582d9ce33e0478a1a5e"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-13.2.0-linux-x64-cflinuxfs3-fd282407.tgz"
    version = "13.2.0"

  [[metadata.dependencies]]
    id = "node"
    name = "Node Engine"
    sha256 = "155b0510732d2f48150dc6bc4b25eb44ce5cd54d21c70d2ca7f31be3b9ab7fa6"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://nodejs.org/dist/v13.3.0/node-v13.3.0-linux-x64.tar.gz"
    version = "13.3.0"

  [[metadata.dependencies]]
    id = "node"
    name = "Node Engine"
    sha256 = "8aa3e5d979e1903e6e95294f666ca4ea42c67b958a6dac4b37f3fb77e34b7a6c"
    source = "https://nodejs.org/dist/v13.3.0/node-v13.3.0.tar.gz"
    source_sha256 = "cab5bd4712265745cfce1416ea0f425f1de71452f0ddc544d815aacee2aede3e"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-13.3.0-linux-x64-cflinuxfs3-8aa3e5d9.tgz"
    version = "13.3.0"

  [[metadata.dependency_deprecation_dates]]
    date = 2021-04-01T00:00:00Z
    link = "https://github.com/nodejs/Release"
    name = "node"
    version_line = "10.x.x"

  [[metadata.dependency_deprecation_dates]]
    date = 2022-04-01T00:00:00Z
    link = "https://github.com/nodejs/Release"
    name = "node"
    version_line = "12.x.x"

  [[metadata.dependency_deprecation_dates]]
    date = 2020-06-01T00:00:00Z
    link = "https://github.com/nodejs/Release"
    name = "node"
    version_line = "13.x.x"

  [[metadata.dependency_deprecation_dates]]
    date = 2019-12-01T00:00:00Z
    link = "https://github.com/nodejs/Release"
    name = "node"
    version_line = "8.x.x"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"
