
[buildpack]
id = "org.cloudfoundry.buildpacks.nodejs"
name = "Node.js Buildpack"
version = "1.6.32"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "26921908430c3749c93bdc4bc21ba0ff6dbfda4dc36d6a3c5f086fab7f10c378"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-6.14.3-linux-x64-cflinuxfs3-26921908.tgz"
version = "6.14.3"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "b1f0f41f51c1153defc8d15fd260782d5df3108882591887953747dce8183819"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-6.14.4-linux-x64-cflinuxfs3-b1f0f41f.tgz"
version = "6.14.4"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "c645a4da0d1276995da83e41f4e9781d1eb08cd3e3b828dac318a9072749bebd"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-8.11.4-linux-x64-cflinuxfs3-c645a4da.tgz"
version = "8.11.4"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "afec056d008f384cb78c2a1618462bd7be10695ac16faa6dd2f0517d7365ccdf"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-8.12.0-linux-x64-cflinuxfs3-afec056d.tgz"
version = "8.12.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "a7afe5aea16738c92b443b0aced859de422447dfb6da8d23d8c95e78e238f3d6"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-9.11.1-linux-x64-cflinuxfs3-a7afe5ae.tgz"
version = "9.11.1"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "86e844f98106131e3e2e05c54baa900ecc21294b73b78e2fc79ca39fe93b7b34"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-9.11.2-linux-x64-cflinuxfs3-86e844f9.tgz"
version = "9.11.2"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "721fa3f14e81190857756e9aaef3e2cc279141a33177d92a854e6a6dfa738da8"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-10.10.0-linux-x64-cflinuxfs3-721fa3f1.tgz"
version = "10.10.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "001127c04d8cfb541df44053796144e6fb6dcdf89b4076edd3286aeff0b13a29"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-10.11.0-linux-x64-cflinuxfs3-001127c0.tgz"
version = "10.11.0"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
id = "io.buildpacks.stacks.bionic"
