
[buildpack]
id = "org.cloudfoundry.buildpacks.nodejs"
name = "Node.js Buildpack"
version = "0.0.7"

[metadata]
include_files = ["bin/build","bin/detect","buildpack.toml","go.mod","go.sum"]
pre_package = "./scripts/build.sh"

[metadata.default_versions]
node = "6.16.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "547422724489a5391d4a137cd130020c73f8f8c721754c67c7692003fe2b6015"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v6.17.0/node-v6.17.0-linux-x64.tar.gz"
version = "6.17.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "d510e3a24c7b617eaf46b166621c6978ebc7fd175e63ef8a970128c9c14edbd8"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-6.17.0-linux-x64-cflinuxfs2-d510e3a2.tgz"
version = "6.17.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "7d9e14363e41e8e74610657c7dc08921486680350b8522d2981d50e9a0eb538f"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-6.17.0-linux-x64-cflinuxfs3-7d9e1436.tgz"
version = "6.17.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "6b2b0613f56e1630edcfc8e7800f87d5538cef09fce6a08f1cc35983181d96b2"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v6.17.1/node-v6.17.1-linux-x64.tar.gz"
version = "6.17.1"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "044c98dc6f91403b90191716a4756a2d196df2a45e261788d83b9784ad469628"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-6.17.1-linux-x64-cflinuxfs2-044c98dc.tgz"
version = "6.17.1"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "8b899102f6459524cc721e2fe4f1e1e1f423eb8da55fc24998921c516f5f1404"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-6.17.1-linux-x64-cflinuxfs3-8b899102.tgz"
version = "6.17.1"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "dc004e5c0f39c6534232a73100c194bc1446f25e3a6a39b29e2000bb3d139d52"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v8.15.0/node-v8.15.0-linux-x64.tar.gz"
version = "8.15.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "1e19815bf98e0555a9f6cbdb6b3031611718a38cacf7704ffb904be5a7bb9e58"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-8.15.0-linux-x64-cflinuxfs2-1e19815b.tgz"
version = "8.15.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "974131821556a7272c9025766ab6620e059068c5eb5418eb72abc6c397bac12d"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-8.15.0-linux-x64-cflinuxfs3-97413182.tgz"
version = "8.15.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "16e203f2440cffe90522f1e1855d5d7e2e658e759057db070a3dafda445d6d1f"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v8.15.1/node-v8.15.1-linux-x64.tar.gz"
version = "8.15.1"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "ed20b1fb7feac745e0c5a221caa907f1f66f77c2de2ac9f1e6edb06448f71575"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-8.15.1-linux-x64-cflinuxfs2-ed20b1fb.tgz"
version = "8.15.1"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "bed0d0e675f46be256f292e2bf693e59a82ea46eb4d9d593575483d0c4428312"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-8.15.1-linux-x64-cflinuxfs3-bed0d0e6.tgz"
version = "8.15.1"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "331f06e2a5fdeeb0f681adce81bc07682bac0418c114f775d07cdabaa0808726"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-10.14.2-linux-x64-cflinuxfs2-331f06e2.tgz"
version = "10.14.2"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "d1a7fed0e8d379dbd588f67cba937ab87021360e43d8960466f73ece91f6ea41"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-10.15.0-linux-x64-cflinuxfs2-d1a7fed0.tgz"
version = "10.15.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "65e66599b275e2c41a882610a841a990e0570ed03bfccc378e031c475a3dae52"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v10.15.2/node-v10.15.2-linux-x64.tar.gz"
version = "10.15.2"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "05ea28a3aeb2ebde8ba0a6aa06c040f6ab7a6da03bbf20400680d9a1938f5984"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-10.15.2-linux-x64-cflinuxfs3-05ea28a3.tgz"
version = "10.15.2"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "6c35b85a7cd4188ab7578354277b2b2ca43eacc864a2a16b3669753ec2369d52"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v10.15.3/node-v10.15.3-linux-x64.tar.gz"
version = "10.15.3"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "52dbc618aa035840763c991688de7aeed0be2eff9d115cddcd09e09055266620"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-10.15.3-linux-x64-cflinuxfs3-52dbc618.tgz"
version = "10.15.3"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "23cafb97f7e299c125b3c45cef3f7cb08ffd37e1aa9372367e715d89a1fa33ca"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v11.13.0/node-v11.13.0-linux-x64.tar.gz"
version = "11.13.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "8e548206203aefb9942f04de4f69c61b8345939529ef7d42067b62629e794629"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-11.13.0-linux-x64-cflinuxfs3-8e548206.tgz"
version = "11.13.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "0d5c078137c992a919898c8fda7e5af40118f355bb938fccfd5aecddaf2dc123"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v11.14.0/node-v11.14.0-linux-x64.tar.gz"
version = "11.14.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "c352f13e9701b052e88b5241af1d89e928d900cdf2cd470607e53da3fb0a854d"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-11.14.0-linux-x64-cflinuxfs3-c352f13e.tgz"
version = "11.14.0"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs2"

[[stacks]]
id = "io.buildpacks.stacks.bionic"
