
[buildpack]
id = "org.cloudfoundry.buildpacks.nodejs"
name = "Node.js Buildpack"
version = "0.0.1"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "d394ea61a51ba3c070838f8696a38f9e47be55af6978e7a074addb742ba0cddc"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v6.14.4/node-v6.14.4-linux-x86.tar.gz"
version = "6.14.4"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "48a4a12d08dd067dedd8bf440e259dd853b77298e78fe80f702627c1ca4a54b6"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-6.14.4-linux-x64-cflinuxfs2-48a4a12d.tgz"
version = "6.14.4"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "b1f0f41f51c1153defc8d15fd260782d5df3108882591887953747dce8183819"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-6.14.4-linux-x64-cflinuxfs3-b1f0f41f.tgz"
version = "6.14.4"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "4ef04373b2005a55aeaff24bc896f2045951d1909e7c1ac38ba4d1e5c9e85626"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v6.15.0/node-v6.15.0-linux-x64.tar.gz"
version = "6.15.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "0f7773d9d19865132c4eb47e0b2dc3f72cb3c69cfda5133fad0843da9e8ff483"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-6.15.0-linux-x64-cflinuxfs2-0f7773d9.tgz"
version = "6.15.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "ac1fb36492172a1af1bbc7a907c6fde059e6c838e301fbaf4e79fe5fc889321c"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-6.15.0-linux-x64-cflinuxfs3-ac1fb364.tgz"
version = "6.15.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "0c5ff3e3223cd1aaa6ca4aad30fb7c94596422d5c1a4dcc4b1a5b4e118a00273"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v8.13.0/node-v8.13.0-linux-x64.tar.gz"
version = "8.13.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "1fd67fc4b59e124d4cf80d83662a9ebf6e0bbfa0e437922198b8f006391d2ab3"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-8.13.0-linux-x64-cflinuxfs2-1fd67fc4.tgz"
version = "8.13.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "21cca77c5ea35434d8104398928fe3f58df75504969140402bbab1d297330211"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-8.13.0-linux-x64-cflinuxfs3-21cca77c.tgz"
version = "8.13.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "bbf81603a924bf86c64da520f6b2a923e6f78e987bb36a58bdb8ff2606d7f995"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v8.14.0/node-v8.14.0-linux-x64.tar.gz"
version = "8.14.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "f450e31f62ea241cf5f07d18564808a2d4652a0a5529ae81cba4c688b9286f81"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-8.14.0-linux-x64-cflinuxfs2-f450e31f.tgz"
version = "8.14.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "144850647960dc5f5fc73fafe8279326e2936d892bb658ee73ff5b0b8fa4a2b5"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-8.14.0-linux-x64-cflinuxfs3-14485064.tgz"
version = "8.14.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "c15307591aad4b65e984a3c25f39f5d102524190c1859a3fb7de166ac5e2641c"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v9.11.1/node-v9.11.1-linux-x86.tar.gz"
version = "9.11.1"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "a008671311b82aac5d30a0c1f40b55f80b79406da9f0f11fd1df5b4d7cfd882b"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-9.11.1-linux-x64-cflinuxfs2-a0086713.tgz"
version = "9.11.1"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "a7afe5aea16738c92b443b0aced859de422447dfb6da8d23d8c95e78e238f3d6"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-9.11.1-linux-x64-cflinuxfs3-a7afe5ae.tgz"
version = "9.11.1"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "166cc28bd9c8217c533b2921edd5e980b14f1d670d828e9d40c1d5b37f51496d"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v9.11.2/node-v9.11.2-linux-x64.tar.gz"
version = "9.11.2"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "58d0bbd00dce33927281735870b490175f1135e7ac927cb2ac30edf744476474"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-9.11.2-linux-x64-cflinuxfs2-58d0bbd0.tgz"
version = "9.11.2"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "86e844f98106131e3e2e05c54baa900ecc21294b73b78e2fc79ca39fe93b7b34"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-9.11.2-linux-x64-cflinuxfs3-86e844f9.tgz"
version = "9.11.2"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "8d13d57aaf95177e97d29c0944d79a17de8c3a31ba3fe88d1846cfd907e52111"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v10.12.0/node-v10.12.0-linux-x64.tar.gz"
version = "10.12.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "94e3b9e92d5c898b1c7cf55f7e53b3aee1fc79fdbed17d1977fe95a2b7e1b463"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-10.12.0-linux-x64-cflinuxfs2-94e3b9e9.tgz"
version = "10.12.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "b702b09eb7198cec42cc2268088ceff3f52961cd52050fc9a312a0ec941a4363"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-10.12.0-linux-x64-cflinuxfs3-b702b09e.tgz"
version = "10.12.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "b4b5d8f73148dcf277df413bb16827be476f4fa117cbbec2aaabc8cc0a8588e1"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v10.13.0/node-v10.13.0-linux-x64.tar.gz"
version = "10.13.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "44945a3388d623116c887357732a9547bfeb7269773f83b35eb65c1d165271ce"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-10.13.0-linux-x64-cflinuxfs2-44945a33.tgz"
version = "10.13.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "941d707aaa07d6bdfc93710fd86296f0f4a720ad0b45a38410e00bd2344c8edc"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-10.13.0-linux-x64-cflinuxfs3-941d707a.tgz"
version = "10.13.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "07dce63fa4be086e4bfeb213a9a3e964f52d0fad2461da2adbf4f9e5540190ca"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-11.1.0-linux-x64-cflinuxfs2-07dce63f.tgz"
version = "11.1.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "2528f860cb0d33fe2f807f56dac347730f32772b9f987f8ec379af9277cae71f"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v11.2.0/node-v11.2.0-linux-x64.tar.gz"
version = "11.2.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "e548fb0b1653fa455762bfffa95334412a0fe66e2b3c330af4b476ac07c8a60f"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-11.2.0-linux-x64-cflinuxfs3-e548fb0b.tgz"
version = "11.2.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "aac519aac1814e8590cd6b55fb2c6ddc1bbb825fc8c097abce5f5361aea61108"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v11.3.0/node-v11.3.0-linux-x64.tar.gz"
version = "11.3.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "9e94f8dc5fc343bd9bd85ea807fc20b786effb29e6fa4ce203fe9b3324b93e12"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-11.3.0-linux-x64-cflinuxfs3-9e94f8dc.tgz"
version = "11.3.0"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs2"

[[stacks]]
id = "io.buildpacks.stacks.bionic"
