api = "0.2"

[buildpack]
id = "org.cloudfoundry.node-engine"
name = "Node Engine Buildpack"
version = "{{ .Version }}"

[metadata]
include_files = ["bin/build","bin/detect","buildpack.toml"]
pre_package = "./scripts/build.sh"

[metadata.default-versions]
node = "10.x"

[[metadata.dependencies]]
id = "node"
name = "Node Engine"
sha256 = "b391450e0fead11f61f119ed26c713180cfe64b363cd945bac229130dfab64fa"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v8.16.0/node-v8.16.0-linux-x64.tar.gz"
version = "8.16.0"

[[metadata.dependencies]]
id = "node"
name = "Node Engine"
sha256 = "f190a0786c817d7749c3ec6e294f284104cd9a594e1989c59cafe08b41fe347c"
source = "https://nodejs.org/dist/v8.16.0/node-v8.16.0.tar.gz"
source_sha256 = "a1a885add3e511177f05676f0834df710886b68cb559b893169f8674a23adfcf"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-8.16.0-linux-x64-cflinuxfs2-f190a078.tgz"
version = "8.16.0"

[[metadata.dependencies]]
id = "node"
name = "Node Engine"
sha256 = "319b5cd2ca0172c4d427fd4f67df858756f04dff04f92670a4658703b9f03a75"
source = "https://nodejs.org/dist/v8.16.0/node-v8.16.0.tar.gz"
source_sha256 = "a1a885add3e511177f05676f0834df710886b68cb559b893169f8674a23adfcf"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-8.16.0-linux-x64-cflinuxfs3-319b5cd2.tgz"
version = "8.16.0"

[[metadata.dependencies]]
id = "node"
name = "Node Engine"
sha256 = "8ef575b64edbb6c04e506d8c8e0c5f92b90f4752841892c5adbb3a1e02863f46"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v8.16.1/node-v8.16.1-linux-x64.tar.gz"
version = "8.16.1"

[[metadata.dependencies]]
id = "node"
name = "Node Engine"
sha256 = "fbbdac757c69cf3ea80031ac916f99e768773ec74d3ffd38c6308b99e02414ee"
source = "https://nodejs.org/dist/v8.16.1/node-v8.16.1.tar.gz"
source_sha256 = "7666207212ac5cbd766b052951f57da62aaa641fedf83fabcb31dbb19f61169d"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-8.16.1-linux-x64-cflinuxfs3-fbbdac75.tgz"
version = "8.16.1"

[[metadata.dependencies]]
id = "node"
name = "Node Engine"
sha256 = "2779d04b1a9744bbb003a1a4476db2444b5f697034bc902a07dde4a8669ae6d0"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v10.16.2/node-v10.16.2-linux-x64.tar.gz"
version = "10.16.2"

[[metadata.dependencies]]
id = "node"
name = "Node Engine"
sha256 = "9d21a165fedeccc9ffdd50657e51312e83ce7204370434d1cba9d02dc728c50a"
source = "https://nodejs.org/dist/v10.16.2/node-v10.16.2.tar.gz"
source_sha256 = "5936ef12ab3f0ce5fbb6751c1bb41f626b6058f414a297b3d8c5eb418a27e8fe"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-10.16.2-linux-x64-cflinuxfs3-9d21a165.tgz"
version = "10.16.2"

[[metadata.dependencies]]
id = "node"
name = "Node Engine"
sha256 = "2f0397bb81c1d0c9901b9aff82a933257bf60f3992227b86107111a75b9030d9"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v10.16.3/node-v10.16.3-linux-x64.tar.gz"
version = "10.16.3"

[[metadata.dependencies]]
id = "node"
name = "Node Engine"
sha256 = "33294d3658fe726d2d035092c72d150b7bd7b6d7de2ecab8fed66862f1f6bafd"
source = "https://nodejs.org/dist/v10.16.3/node-v10.16.3.tar.gz"
source_sha256 = "db5a5e03a815b84a1266a4b48bb6a6d887175705f84fd2472f0d28e5e305a1f8"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-10.16.3-linux-x64-cflinuxfs3-33294d36.tgz"
version = "10.16.3"

[[metadata.dependencies]]
id = "node"
name = "Node Engine"
sha256 = "5488e9d9e860eb344726aabdc8f90d09e36602da38da3d16a7ee852fd9fbd91f"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v12.9.1/node-v12.9.1-linux-x64.tar.gz"
version = "12.9.1"

[[metadata.dependencies]]
id = "node"
name = "Node Engine"
sha256 = "a22a1fc1b6b29ddea779cd4ffba0754fb6db137180fbe4b1e4e3db2b81d55701"
source = "https://nodejs.org/dist/v12.9.1/node-v12.9.1.tar.gz"
source_sha256 = "9150b2b3c728e022c596ab86188c685facc9f30f4c8e60c1a0f9d5a3e8e3653f"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-12.9.1-linux-x64-cflinuxfs3-a22a1fc1.tgz"
version = "12.9.1"

[[metadata.dependencies]]
id = "node"
name = "Node Engine"
sha256 = "3de23fd9f2145ff76d0583e7f57aa4ccead58b3fb991e215f862e779c9cdf151"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v12.10.0/node-v12.10.0-linux-x64.tar.gz"
version = "12.10.0"

[[metadata.dependencies]]
id = "node"
name = "Node Engine"
sha256 = "d99cc0e35a0c79d830c388943c65ac7327955af9a5828e50da6cec67d719bb09"
source = "https://nodejs.org/dist/v12.10.0/node-v12.10.0.tar.gz"
source_sha256 = "371a3e39f1a14adbd7b37dee57641075ccfa240bd990630ff213298f16ad49b4"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-12.10.0-linux-x64-cflinuxfs3-d99cc0e3.tgz"
version = "12.10.0"

[[metadata.dependency_deprecation_dates]]
date = 2021-04-01T00:00:00Z
link = "https://github.com/nodejs/Release"
name = "node"
version_line = "10.x.x"

[[metadata.dependency_deprecation_dates]]
date = 2020-04-01T00:00:00Z
link = "https://github.com/nodejs/Release"
name = "node"
version_line = "12.x.x"

[[metadata.dependency_deprecation_dates]]
date = 2019-12-01T00:00:00Z
link = "https://github.com/nodejs/Release"
name = "node"
version_line = "8.x.x"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
id = "io.buildpacks.stacks.bionic"
