
[buildpack]
id = "org.cloudfoundry.buildpacks.nodejs"
name = "Node.js Buildpack"
version = "0.0.1"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "4ef04373b2005a55aeaff24bc896f2045951d1909e7c1ac38ba4d1e5c9e85626"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v6.15.0/node-v6.15.0-linux-x64.tar.gz"
version = "6.15.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "0f7773d9d19865132c4eb47e0b2dc3f72cb3c69cfda5133fad0843da9e8ff483"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-6.15.0-linux-x64-cflinuxfs2-0f7773d9.tgz"
version = "6.15.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "ac1fb36492172a1af1bbc7a907c6fde059e6c838e301fbaf4e79fe5fc889321c"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-6.15.0-linux-x64-cflinuxfs3-ac1fb364.tgz"
version = "6.15.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "aa8ef47382853d7124110203c3773515cff00737f1cd7bce98bd388603141c6d"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v6.15.1/node-v6.15.1-linux-x64.tar.gz"
version = "6.15.1"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "16abb1a8bcef1bc6339a738b51f5f2a5e7d48f820da2cec3f4912504517f7490"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-6.15.1-linux-x64-cflinuxfs2-16abb1a8.tgz"
version = "6.15.1"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "c8da2b6c146c4bf3c72b35a879be1a5e6764229702ddf3b0ca159ed74debd381"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-6.15.1-linux-x64-cflinuxfs3-c8da2b6c.tgz"
version = "6.15.1"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "0c5ff3e3223cd1aaa6ca4aad30fb7c94596422d5c1a4dcc4b1a5b4e118a00273"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v8.13.0/node-v8.13.0-linux-x64.tar.gz"
version = "8.13.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "1fd67fc4b59e124d4cf80d83662a9ebf6e0bbfa0e437922198b8f006391d2ab3"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-8.13.0-linux-x64-cflinuxfs2-1fd67fc4.tgz"
version = "8.13.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "21cca77c5ea35434d8104398928fe3f58df75504969140402bbab1d297330211"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-8.13.0-linux-x64-cflinuxfs3-21cca77c.tgz"
version = "8.13.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "bbf81603a924bf86c64da520f6b2a923e6f78e987bb36a58bdb8ff2606d7f995"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v8.14.0/node-v8.14.0-linux-x64.tar.gz"
version = "8.14.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "f450e31f62ea241cf5f07d18564808a2d4652a0a5529ae81cba4c688b9286f81"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-8.14.0-linux-x64-cflinuxfs2-f450e31f.tgz"
version = "8.14.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "144850647960dc5f5fc73fafe8279326e2936d892bb658ee73ff5b0b8fa4a2b5"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-8.14.0-linux-x64-cflinuxfs3-14485064.tgz"
version = "8.14.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "c15307591aad4b65e984a3c25f39f5d102524190c1859a3fb7de166ac5e2641c"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v9.11.1/node-v9.11.1-linux-x86.tar.gz"
version = "9.11.1"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "a008671311b82aac5d30a0c1f40b55f80b79406da9f0f11fd1df5b4d7cfd882b"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-9.11.1-linux-x64-cflinuxfs2-a0086713.tgz"
version = "9.11.1"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "a7afe5aea16738c92b443b0aced859de422447dfb6da8d23d8c95e78e238f3d6"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-9.11.1-linux-x64-cflinuxfs3-a7afe5ae.tgz"
version = "9.11.1"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "166cc28bd9c8217c533b2921edd5e980b14f1d670d828e9d40c1d5b37f51496d"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v9.11.2/node-v9.11.2-linux-x64.tar.gz"
version = "9.11.2"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "58d0bbd00dce33927281735870b490175f1135e7ac927cb2ac30edf744476474"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-9.11.2-linux-x64-cflinuxfs2-58d0bbd0.tgz"
version = "9.11.2"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "86e844f98106131e3e2e05c54baa900ecc21294b73b78e2fc79ca39fe93b7b34"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-9.11.2-linux-x64-cflinuxfs3-86e844f9.tgz"
version = "9.11.2"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "2f10d1a5d211a150d6813bdca8f3b1fe673a68fd534b1f547befec1314244596"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v10.14.0/node-v10.14.0-linux-x64.tar.gz"
version = "10.14.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "7ed8093c196e66fa639ea1467c12eb3d5673157c9db89111c69bd805642abd4a"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-10.14.0-linux-x64-cflinuxfs2-7ed8093c.tgz"
version = "10.14.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "72f3ac305982ba4b727be462c90cb1f5eb4394e3f7e193636242c3b1b4f039be"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-10.14.0-linux-x64-cflinuxfs3-72f3ac30.tgz"
version = "10.14.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "2cc1a9b118e5d660cd6611c808f0cd80821c79ea5990c221b78124770f4dc38e"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v10.14.1/node-v10.14.1-linux-x64.tar.gz"
version = "10.14.1"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "53066dffbe52a6d7c0fd65efb9733313d39e2cde191b5d3a6a56325626c921ba"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-10.14.1-linux-x64-cflinuxfs2-53066dff.tgz"
version = "10.14.1"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "f1aac86c19f19e24f01581491b45593a7eabdfed3c67bb301d02d36bdaced0ef"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-10.14.1-linux-x64-cflinuxfs3-f1aac86c.tgz"
version = "10.14.1"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "07dce63fa4be086e4bfeb213a9a3e964f52d0fad2461da2adbf4f9e5540190ca"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-11.1.0-linux-x64-cflinuxfs2-07dce63f.tgz"
version = "11.1.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "aac519aac1814e8590cd6b55fb2c6ddc1bbb825fc8c097abce5f5361aea61108"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v11.3.0/node-v11.3.0-linux-x64.tar.gz"
version = "11.3.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "9e94f8dc5fc343bd9bd85ea807fc20b786effb29e6fa4ce203fe9b3324b93e12"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-11.3.0-linux-x64-cflinuxfs3-9e94f8dc.tgz"
version = "11.3.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "4ef7dea131453da3a93cc1f32bff948da8953958dcbe3b413debae8bb41aa7a0"
stacks = ["io.buildpacks.stacks.bionic"]
uri = "https://nodejs.org/dist/v11.4.0/node-v11.4.0-linux-x64.tar.gz"
version = "11.4.0"

[[metadata.dependencies]]
id = "node"
name = "NodeJS"
sha256 = "f2fdd6a5da62ad3f28a5b9385cfde89d18a0ecce146c12787a7c77faa6996678"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node-11.4.0-linux-x64-cflinuxfs3-f2fdd6a5.tgz"
version = "11.4.0"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs2"

[[stacks]]
id = "io.buildpacks.stacks.bionic"
